# Generated by Django 5.2.8 on 2025-11-18 20:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        editable=False,
                        help_text="Username autogenerado desde email",
                        max_length=150,
                        unique=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email @10code.es para autenticación",
                        max_length=254,
                        unique=True,
                        verbose_name="Email corporativo",
                    ),
                ),
                ("first_name", models.CharField(max_length=150, verbose_name="Nombre")),
                ("last_name", models.CharField(max_length=150, verbose_name="Apellidos")),
                (
                    "avatar_url",
                    models.URLField(
                        blank=True,
                        help_text="URL del avatar de Google",
                        null=True,
                        verbose_name="Avatar",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("is_staff", models.BooleanField(default=False, verbose_name="Staff")),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Fecha de registro"
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="Último login"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "db_table": "users",
                "ordering": ["-date_joined"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Fecha y hora de creación del registro",
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Última modificación",
                        verbose_name="Fecha de actualización",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("login_failed", "Login fallido"),
                            ("user_created", "Usuario creado"),
                            ("user_updated", "Usuario actualizado"),
                            ("user_deactivated", "Usuario desactivado"),
                            ("role_assigned", "Rol asignado"),
                            ("role_removed", "Rol removido"),
                            ("permission_change", "Cambio de permisos"),
                        ],
                        db_index=True,
                        max_length=50,
                        verbose_name="Acción",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        blank=True,
                        help_text="Ej: User, Role, Project",
                        max_length=100,
                        verbose_name="Tipo de recurso",
                    ),
                ),
                (
                    "resource_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="ID del objeto afectado",
                        null=True,
                        verbose_name="ID del recurso",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Información adicional JSON",
                        verbose_name="Metadatos",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP del cliente",
                        null=True,
                        verbose_name="Dirección IP",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Fecha y hora",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la acción (null para eventos del sistema)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Auditoría",
                "verbose_name_plural": "Logs de Auditoría",
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="GoogleProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Fecha y hora de creación del registro",
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Última modificación",
                        verbose_name="Fecha de actualización",
                    ),
                ),
                (
                    "google_id",
                    models.CharField(
                        help_text="ID único de Google",
                        max_length=255,
                        unique=True,
                        verbose_name="Google ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email verificado de Google",
                        max_length=254,
                        verbose_name="Email de Google",
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Datos extra del perfil",
                        verbose_name="Datos raw",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Google",
                "verbose_name_plural": "Perfiles de Google",
                "db_table": "google_profiles",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Fecha y hora de creación del registro",
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Última modificación",
                        verbose_name="Fecha de actualización",
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        help_text="Código único del rol", unique=True, verbose_name="Código"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre descriptivo", max_length=100, verbose_name="Nombre"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descripción")),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="Roles predefinidos no editables",
                        verbose_name="Rol del sistema",
                    ),
                ),
                (
                    "parent_role",
                    models.ForeignKey(
                        blank=True,
                        help_text="Rol del que hereda permisos",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_roles",
                        to="accounts.role",
                        verbose_name="Rol padre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rol",
                "verbose_name_plural": "Roles",
                "db_table": "roles",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "permission_code",
                    models.CharField(
                        help_text="Formato: app.action_model (ej: projects.add_project)",
                        max_length=100,
                        verbose_name="Código de permiso",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="accounts.role",
                        verbose_name="Rol",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permiso",
                "verbose_name_plural": "Permisos",
                "db_table": "permissions",
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Fecha y hora de creación del registro",
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Última modificación",
                        verbose_name="Fecha de actualización",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Fecha de asignación",
                        verbose_name="Asignado el",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        help_text="Usuario que asignó el rol",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="roles_assigned",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Asignado por",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_users",
                        to="accounts.role",
                        verbose_name="Rol",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rol de Usuario",
                "verbose_name_plural": "Roles de Usuarios",
                "db_table": "user_roles",
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_email_4b85f2_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["is_active"], name="users_is_acti_847b48_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["user", "timestamp"], name="audit_logs_user_id_88267f_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["action", "timestamp"], name="audit_logs_action_474804_idx"),
        ),
        migrations.AddIndex(
            model_name="googleprofile",
            index=models.Index(fields=["google_id"], name="google_prof_google__6601eb_idx"),
        ),
        migrations.AddIndex(
            model_name="permission",
            index=models.Index(
                fields=["role", "permission_code"], name="permissions_role_id_304b6a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="permission",
            constraint=models.UniqueConstraint(
                fields=("role", "permission_code"), name="unique_role_permission"
            ),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(fields=["user", "role"], name="user_roles_user_id_801a9e_idx"),
        ),
        migrations.AddConstraint(
            model_name="userrole",
            constraint=models.UniqueConstraint(fields=("user", "role"), name="unique_user_role"),
        ),
    ]
