# Generated by Django 5.2.8 on 2025-11-18 20:02

from django.db import migrations


def populate_default_roles(apps, schema_editor):
    """
    Crea los roles predefinidos del sistema.

    Basado en el FSD de Autenticación y Usuarios v1.3:
    - superadmin: Acceso total al sistema
    - admin: Gestión de configuración y usuarios
    - project_manager: Gestión de proyectos
    - developer: Desarrollo y tareas
    - commercial: Gestión comercial
    - hr: Recursos humanos
    - employee: Usuario base
    """
    Role = apps.get_model("accounts", "Role")

    roles = [
        {
            "code": "superadmin",
            "name": "Super Administrador",
            "description": "Acceso total al sistema. Rol reservado para el propietario de 10Code.",
            "is_system": True,
        },
        {
            "code": "admin",
            "name": "Administrador",
            "description": "Gestión de configuración del sistema y usuarios. No tiene acceso a datos financieros sensibles.",
            "is_system": True,
        },
        {
            "code": "project_manager",
            "name": "Project Manager",
            "description": "Gestión de proyectos, equipos y asignación de recursos. Puede ver datos financieros de sus proyectos.",
            "is_system": True,
        },
        {
            "code": "developer",
            "name": "Desarrollador",
            "description": "Acceso a proyectos asignados, tareas, imputación de tiempos y backlog. Sin acceso a datos financieros.",
            "is_system": True,
        },
        {
            "code": "commercial",
            "name": "Comercial",
            "description": "Gestión de oportunidades, estimaciones, funnel comercial y ofertas. Acceso a módulo de estimación CEPF.",
            "is_system": True,
        },
        {
            "code": "hr",
            "name": "Recursos Humanos",
            "description": "Gestión de empleados, control horario, ausencias y capacidad. Acceso total a módulo RR.HH.",
            "is_system": True,
        },
        {
            "code": "employee",
            "name": "Empleado",
            "description": "Rol base para todos los empleados. Acceso a perfil, control horario personal y notificaciones.",
            "is_system": True,
        },
    ]

    for role_data in roles:
        Role.objects.get_or_create(
            code=role_data["code"],
            defaults={
                "name": role_data["name"],
                "description": role_data["description"],
                "is_system": role_data["is_system"],
            },
        )


def reverse_populate_roles(apps, schema_editor):
    """Elimina los roles predefinidos del sistema."""
    Role = apps.get_model("accounts", "Role")
    Role.objects.filter(is_system=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_auth_models_initial"),
    ]

    operations = [
        migrations.RunPython(populate_default_roles, reverse_code=reverse_populate_roles),
    ]
