# Generated by Django 5.2.8 on 2025-11-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_populate_default_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="Fecha de nacimiento"),
        ),
    ]
