# Generated by Django 5.2.8 on 2025-12-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Imagen subida por el usuario",
                null=True,
                upload_to="avatars/",
                verbose_name="Avatar (Imagen)",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar_url",
            field=models.URLField(
                blank=True,
                help_text="URL del avatar de Google",
                null=True,
                verbose_name="Avatar (URL)",
            ),
        ),
    ]
